### PR TITLE
Update dependencies and regenerate docs

### PR DESCRIPTION
**Pull request by abdonrd**
Also re-format, re-generate docs and split `lint` script.

### CODE REVIEW

**Comment by arthurevans** [comment]
I don't have any opinions here, so punting to @justinfagnani

**Comment by arthurevans** [comment]
I updated the dependencies in the [JS version](https://github.com/PolymerLabs/lit-element-starter-js/pull/1) to match these and they seem to work fine.

On the formatting, I defer to @justinfagnani

**Comment by abdonrd** [comment]
@arthurevans this JS version is private :)

And about the formatting, I just run your `npm run format` task (https://github.com/PolymerLabs/lit-element-starter-ts/pull/18/commits/eb3be067b92dab552ed6b83eb2a593dede71cdde).

**Comment by justinfagnani** [comment]
LGTM, although IMO it's probably not a great idea to bump the `lit-element` dependency. There's nothing in the starter kit that requires 2.3.1, and you generally want to have the lowest lower bound that's compatible to avoid incompatible versions across multiple dependents.

**Pull request merged**
